### ISSUE TITLE
Getting Error while creating pdf report

### ISSUE THREAD

**Issue by shivanipacharne-eaton** [pentaho/pentaho-reporting#1702]
I'm using pentaho-reporting-engine-classic-core-7.0.0.5-89.jar in my project to generate pdf reports.
One of my report is not generating in pdf but csv reports are generating with the same OutputStream.

Error log :
```2024-10-01 14:25:58,087 IST [https-openssl-nio-443-exec-5] ERROR com.cannontech.web.util.ErrorHelperFilter - Servlet error filter caught an exception processing {YK3560406744}: contextPath=/yukon; pathInfo=null; parameters=com.cannontech.yukon.request.csrf.token={0ac1e55e-f661-4485-b633-99f7230c9052},REDIRECT={/analysis/Reports.jsp?groupType=STARS},REFERRER={/analysis/Reports.jsp?groupType=STARS},ecID={4},ACTION={DownloadReport},type={EC_ACTIVITY_LOG_DETAIL},startDate={09/30/2024},stopDate={10/02/2024},ext={pdf},Generate={},actionGroupType={0}; remoteAddr=0:0:0:0:0:0:0:1; requestURL=https://localhost/yukon/servlet/ReportGenerator; queryString=
java.io.IOException: Failed to process the report
	at com.cannontech.analysis.ReportFuncs.outputYukonReport(ReportFuncs.java:200)
	at com.cannontech.servlet.ReportGenerator.doPost(ReportGenerator.java:218)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
```

**Upon investigation**, I found out rootcause of the error is :
```
org.pentaho.reporting.engine.classic.core.InvalidReportStateException: Header and footer consume the whole page. No space left for normal-flow.
```

Could you guide me what things I should check to evaluated and optimize header and footer space??

**Comment by shivanipacharne-eaton** [comment]
Header ad footer set at app side.. found rootcause.

**Comment by shivanipacharne-eaton** [comment]
Header ad footer set at app side.. found rootcause.
